### shipping Service
apiVersion: v1
kind: Service
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080